
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-es
  template:
    metadata:
      labels:
        app: kafka-es
    spec:
      containers:
      - name: kafka-es
        image: registry.cn-shanghai.aliyuncs.com/netis/kafka-es:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-es
spec:
  type: ClusterIP
  ports:
  - port: 1234
    targetPort: 1234
  selector:
    app: kafka-es

