apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tomcat.fullname" . }}
  labels:
    app: {{ template "tomcat.name" . }}
    chart: {{ template "tomcat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "tomcat.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "tomcat.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: app-volume
          emptyDir: {}
        - name: agent-volume
          emptyDir: {}
      initContainers:
        - name: war
          image: {{ .Values.image.webarchive.repository }}:{{ .Values.image.webarchive.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - "cp /*.war /app"
          volumeMounts:
            - name: app-volume
              mountPath: /app
        # - name: swagent
        #   image: {{ .Values.image.swagent.repository }}:{{ .Values.image.swagent.tag }}
        #   imagePullPolicy: {{ .Values.image.pullPolicy }}
        #   command:
        #     - "sh"
        #     - "-c"
        #     - "mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent"
        #   volumeMounts:
        #     - name: agent-volume
        #       mountPath: {{ .Values.swagent.mount }}
      containers:
#         - name: {{ .Values.sidecar.name }}
#           image: {{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}
#     {{- if .Values.sidecar.command }}
#           command:
# {{ toYaml .Values.sidecar.command | indent 12 }}
#     {{- end }}
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.tomcat.repository }}:{{ .Values.image.tomcat.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # env:
          #  - name: JAVA_OPTS
          #    value: {{ .Values.swagent.opts }}
          #  - name: SW_AGENT_NAME
          #    value: {{ .Values.swagent.name }}
          #  - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
          #    value: {{ .Values.swagent.oapserver }} 
          volumeMounts:
            - name: app-volume
              mountPath: {{ .Values.deploy.directory }}
            - name: agent-volume
              mountPath: {{ .Values.swagent.mount }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              #hostPort: 8009
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
