apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: producer
        image: registry.cn-shanghai.aliyuncs.com/netis/kafka-producer:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 1234
      - name: monitor
        image: registry.cn-shanghai.aliyuncs.com/netis/packet-agent:0.3.7
        imagePullPolicy: IfNotPresent
        command:
        - "/usr/local/bin/pktminerg"
        - "-i"
        - "eth0"
        - "-r"
        - "172.18.0.211"
        - "-z"
        - "82"
        
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
spec:
  type: LoadBalancer
  ports:
  - port: 1234
    targetPort: 1234
  selector:
    app: kafka-producer

