apiVersion: v1
kind: Service
metadata:
  labels:
    app: skywalking
    component: oap
  name: skywalking-oap
  namespace: default
spec:
  ports:
  - name: rest
    port: 12800
    protocol: TCP
    targetPort: 12800
  - name: grpc
    port: 11800
    protocol: TCP
    targetPort: 11800
  selector:
    app: skywalking
    component: oap
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skywalking
    component: oap
  name: skywalking-oap
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: skywalking
      component: oap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skywalking
        component: oap
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: skywalking
                  component: oap
                  release: skywalking
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx1g -Xms1g
        - name: SW_CLUSTER
          value: kubernetes
        - name: SW_CLUSTER_K8S_NAMESPACE
          value: default
        - name: SW_CLUSTER_K8S_LABEL
          value: app=skywalking,release=skywalking,component=oap
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: SW_STORAGE
          value: elasticsearch
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: elasticsearch-master:9200
        image: registry.cn-shanghai.aliyuncs.com/netis/skywalking-oap:8.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 12800
        name: oap
        ports:
        - containerPort: 11800
          name: grpc
          protocol: TCP
        - containerPort: 12800
          name: rest
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 12800
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - for i in $(seq 1 60); do nc -z -w3 elasticsearch-master 9200 && exit 0 ||
          sleep 5; done; exit 1
        image: busybox:1.30
        imagePullPolicy: IfNotPresent
        name: wait-for-elasticsearch
        resources: {}
      restartPolicy: Always
      serviceAccount: skywalking-oap
      serviceAccountName: skywalking-oap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: skywalking
  name: skywalking
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: skywalking
  name: skywalking
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skywalking
subjects:
- kind: ServiceAccount
  name: skywalking-oap
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: skywalking
    component: oap
  name: skywalking-oap
  namespace: default